### ISSUE TITLE
One question about previous work

### ISSUE THREAD

**Issue by noticeable** [lhao0301/lhao0301.github.io#1]
您好：
      很冒昧打扰您，我最近正在做Beyond-Frontal-Faces论文的实现，但是在运行作者提供的源码的时候出现了错误，我已经尝试过多次联系原作者但是都没有回复，在closed issue里面看到您的提问，发现您已经成功运行代码了，所以发邮件找到您，希望您能帮助解答，问题我已传上Issue里面去了，您点击以下链接即可转到
https://github.com/sciencefans/Beyond-Frontal-Faces/issues/3

希望能够得到您的回复!谢谢！

**Comment by TX2012LH** [comment]
当时好像我没有用这个repo的code，是参照这个的code实现了一遍；我当时是用的caffe的Python接口，所以没有这个问题。
